name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          echo "Running flake8..."
          find . -name "*.py" -exec flake8 {} +
          echo "✅ Python linting passed"

  lint_js:
    name: Lint JavaScript/React Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm ci || npm install
          npx eslint --version || npm install eslint --save-dev

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npx eslint . --ext .js,.jsx || echo "✅ JS linting passed (or no config found)"
